package io.revx.core.model.targetting;

public enum AdSafetyBWType {
  BW_TYPE_ADVERTISER, BW_TYPE_ADVERTISER_IO, BW_TYPE_ADVERTISER_LI, BW_TYPE_CREATIVE, BW_TYPE_PUBLISHER, BW_TYPE_PUBLISHER_IO, BW_TYPE_PUBLISHER_SECTION, BW_TYPE_DOMAIN
}
